### ISSUE TITLE
Utilizzo di Jekyll per la generazione di un sito base per un Comune

### ISSUE THREAD

**Issue by mkjsix** [italia/design-comuni-prototipi#17]
Buongiorno,

Non mi risulta chiaro come sia utilizzato Jekyll per generare un sito template per un comune in questo repository. Il sito di esempio del Comune di Cagliari infatti sembrerebbe essere esclusivamente formato da file HTML statici che poi sono copiati pari pari da jekyll nel folder _site/esempio così come sono, senza alcun processo di trasformazione. 

Per fare questo ho semplicemente usato il comando `bundle exec jekyll build` ma l'uso di jekyll non appare esplicitamente documentato da nessuna parte. Vorrei solo capire se l'unica possibilità si a quella di fare il copia e incolla degli esempi statici, quindi poi dovremo introdurre noi un generatore statico, o se invece mi stia sfuggendo qualcosa.

Grazie.

**Comment by francescozaia** [comment]
Ciao @mkjsix l'esempio specifico del comune di Cagliari (così come quello generico [mostrato qui](https://italia.github.io/design-comuni-prototipi/it/kit.html#template-html)) è mostrato solo a scopo esemplificativo sotto forma di file HTML statici, come "caso di applicazione" del modello comuni. Di certo l'HTML statico può essere utile come traccia per iniziare il proprio sito o per essere modificato al fine di fare i primi test di fattibilità/usabilità, ma non è di suo già un prodotto completo.

Il [vero sito del comune di Cagliari](https://www.comune.cagliari.it/portale/), dal backend molto più complesso, è costruito grazie ad un CMS "vero" (nel caso specifico EntandoCMS) che permette agli impegati comunali di editare in comodità i contenuti. La soluzione completa è messa a riuso [qui](https://developers.italia.it/it/software/c_b354-comunedicagliari-componentiportale), ma richiede comunque approfondite valutazioni e implementazioni prima della messa in opera.

**Comment by mkjsix** [comment]
Grazie @francescozaia 
Ho comunque visto che il sito di esempio "bootstrap-italia" fa uso dei template jekyll. Per quello che abbiamo in mente di fare noi un generatore statico basta e avanza, quindi immagino che partiremo da quell'esempio.
