### ISSUE TITLE
Rispetto contrasto colori

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/design-comuni-prototipi#4]
Ciao,
Sul prototipo di Cagliari ho riscontrato un insufficiente contrasto colore nei link hover

![immagine](https://user-images.githubusercontent.com/20642463/54536984-020d7500-4992-11e9-83f8-ed9f75dfb770.png)

**Comment by antoniopascalis** [comment]
Buongiorno Alessandro, abbiamo sostituito il color dell’hover #74A681 con #83AF8E. Grazie per la segnalazione.

**Comment by AlessandroVecchi** [comment]
Le linee guida parlano di 4,5:1, io come regola però cerco sempre di mantenere un rapporto 7:1 in modo da essere sicuri che il testo sia sempre leggibili.

**Comment by antoniopascalis** [comment]
per l'over verrà usato questo colore: #BADEC3  Grazie

<img width="477" alt="Schermata 2019-03-19 alle 16 02 43" src="https://user-images.githubusercontent.com/15977201/54616929-bd044400-4a60-11e9-9c68-230ed3c1ea64.png">
